---
application:
  name: "qovery22"
  project: "mygitproj"
  organization: "QoveryCommunity"
databases:
- type: "POSTGRESQL"
  name: "strapi"
  version: "10"
routers:
- name: "main-qovery22"
  routes:
  - application_name: "qovery22"
    paths:
    - "/*"
